# tasks file
---
- name: ib logfile | get datadir
  mysql_variables:
    variable: datadir
  register: _datadir_value
  tags:
    - percona-server-store-datadir
    - percona-server-store-datadir-retrieve

- name: ib logfile | store datadir
  ansible.builtin.set_fact:
    percona_server_datadir: "{{ _datadir_value.msg }}"
  tags:
    - percona-server-store-datadir
    - percona-server-store-datadir-set-fact

# Instead of doing this in main.yml we do it here because of a bug in 2.2.0.0
- block:
    - name: ib logfile | set InnoDB shutdown mode
      mysql_variables:
        variable: innodb_fast_shutdown
        value: "1"
      tags:
        - percona-server-ib-logfile-innodb-fast-shutdown
        - percona-server-ib-logfile-innodb-fast-shutdown-set

    - name: ib logfile | stop service
      ansible.builtin.service:
        name: mysql
        state: stopped
      tags:
        - percona-server-ib-logfile-stop-service

    - name: ib logfile | remove ib_logfile(s)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ percona_server_datadir.rstrip('/') }}/ib_logfile0"
        - "{{ percona_server_datadir.rstrip('/') }}/ib_logfile1"
      tags:
        - percona-server-ib-logfile-remove

    - name: ib logfile | start service
      ansible.builtin.service:
        name: mysql
        state: started
      tags:
        - percona-server-ib-logfile-start-service
  when: _mysqld_installed.rc != 0
