# tasks file for percona-server
---
- name: toolkit udfs | create (lock) directory
  file:
    path: "{{ percona_server_lock_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - percona-server-toolkit-udfs-lock-directory

- name: toolkit udfs | install
  shell: >
    mysql -e "DROP FUNCTION IF EXISTS {{ item.function }}; CREATE FUNCTION {{ item.function }} RETURNS INTEGER SONAME '{{ item.soname }}'" && touch {{ percona_server_lock_path }}/{{ item.soname }}
  args:
    creates: "{{ percona_server_lock_path }}/{{ item.soname }}"
  with_items: "{{ percona_server_toolkit_udfs }}"
  tags:
    - percona-server-toolkit-udfs-install
