# tasks file
---
- name: timezone info | create (lock) directory
  file:
    path: "{{ percona_server_lock_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - percona-server-zoneinfo-lock-directory

- name: timezone info | install
  shell: >
    {{ percona_server_zoneinfo_command }} | tee {{ percona_server_lock_path }}/zoneinfo.sql | mysql --database=mysql
  args:
    executable: /bin/bash
    creates: "{{ percona_server_lock_path }}/zoneinfo.sql"
  tags:
    - percona-server-zoneinfo-install
